bdb/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'bdb.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
)

bmdb/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'bmdb.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),


    ## Section ADMIN ##
    url(r'^admin/', include(admin.site.urls)),

    # API url. parameter 1 is report and 2 is a parameter depending on the report. E.g. search term for search functionality
    url(r'^api/(\w{0,50})/(\w{0,50})/(\w{0,50})/','api.views.report_view'),

    ## Section HOME ##
    url(r'^/home/','web.views.page_home'),

    ## Section FOOD CLAIMS ##
    url(r'^food-claims/$','web.views.page_food_claims'),
    url(r'^updates/$','web.views.page_fc_updates'),
    url(r'^nz---australia-information/$','web.views.page_fc_nz_info'),
    url(r'^world-wide-information/$','web.views.page_fc_world_info'),
    url(r'^food-comp-db/$','web.views.page_fc_food_composition_db'),
    url(r'^making-a-claim/$','web.views.page_fc_make_claim'),

    ## Section DATABASE ##
    url(r'^database/$','web.views.page_database'),
    url(r'^search/$','web.views.page_db_search'),
    url(r'^register/$','web.views.page_db_register'),
    url(r'^faqs/$','web.views.page_db_faq'),

    ## Section ABOUT ##
    url(r'^about/$','web.views.page_about'),
    url(r'^contact/$','web.views.page_ab_contact_us'),
    url(r'^terms---conditions/$','web.views.page_ab_terms'),

    ## Section DATA INPUT ##
    url(r'^data-input$','adm.views.sequencial_data_input'),
)

adm/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Remove `managed = False` lines for those models you wish to give write DB access
# Feel free to rename the models, but don't rename db_table values or field names.
#
# Also note: You'll have to insert the output of 'django-admin.py sqlcustom [appname]'
# into your database.
from __future__ import unicode_literals

from django.db import models

class BdbAttrib(models.Model):
    oid = models.IntegerField(primary_key=True)
    kid = models.ForeignKey('BdbAttribKey', db_column='kid')
    value = models.TextField(blank=True)
    class Meta:
        managed = False
        db_table = 'bdb_attrib'

class BdbAttribKey(models.Model):
    oid = models.IntegerField(primary_key=True)
    fid = models.IntegerField(blank=True, null=True)
    name = models.CharField(max_length=255)
    alias = models.CharField(max_length=255, blank=True)
    descr = models.CharField(max_length=255, blank=True)
    class Meta:
        managed = False
        db_table = 'bdb_attrib_key'

class BdbConfig(models.Model):
    oid = models.IntegerField(primary_key=True)
    fid = models.IntegerField(blank=True, null=True)
    name = models.CharField(max_length=255)
    alias = models.CharField(max_length=255, blank=True)
    descr = models.CharField(max_length=255, blank=True)
    class Meta:
        managed = False
        db_table = 'bdb_config'

class BdbDisease(models.Model):
    oid = models.IntegerField(primary_key=True)
    fid = models.IntegerField(blank=True, null=True)
    name = models.CharField(max_length=255)
    alias = models.CharField(max_length=255, blank=True)
    descr = models.CharField(max_length=255, blank=True)
    class Meta:
        managed = False
        db_table = 'bdb_disease'

class BdbFood(models.Model):
    oid = models.IntegerField(primary_key=True)
    fid = models.IntegerField(blank=True, null=True)
    name = models.CharField(max_length=255)
    alias = models.CharField(max_length=255, blank=True)
    descr = models.CharField(max_length=255, blank=True)
    class Meta:
        managed = False
        db_table = 'bdb_food'

class BdbOb(models.Model):
    oid = models.IntegerField(primary_key=True)
    fid = models.IntegerField(blank=True, null=True)
    name = models.CharField(max_length=255)
    alias = models.CharField(max_length=255, blank=True)
    descr = models.CharField(max_length=255, blank=True)
    class Meta:
        managed = False
        db_table = 'bdb_ob'

class BdbSymtpom(models.Model):
    oid = models.IntegerField(primary_key=True)
    fid = models.IntegerField(blank=True, null=True)
    name = models.CharField(max_length=255)
    alias = models.CharField(max_length=255, blank=True)
    descr = models.CharField(max_length=255, blank=True)
    class Meta:
        managed = False
        db_table = 'bdb_symtpom'

web/templates/page_ab_contact_us.html
{% extends "page_base.html" %}

{% load staticfiles %}
{% load emph %}

{% block content %}
<div class="clearfix colelem" id="u3241-4"><!-- content -->
     <p>Contact Us</p>
</div>
<div style="min-height:500px">
</div>
{% endblock %}

web/templates/page_ab_terms.html
{% extends "page_base.html" %}

{% load staticfiles %}
{% load emph %}

{% block content %}
<div class="clearfix colelem" id="u3241-4"><!-- content -->
     <p>Terms and Conditions</p>
</div>
<div style="min-height:500px">
</div>
{% endblock %}

web/templates/page_about.html
{% extends "page_base.html" %}

{% load staticfiles %}
{% load emph %}

{% block content %}
<div class="clearfix colelem" id="u3241-4"><!-- content -->
     <p>About</p>
</div>
<div style="min-height:500px">
</div>
{% endblock %}

web/templates/page_database.html
{% extends "page_base.html" %}

{% load staticfiles %}
{% load emph %}

{% block content %}
<div class="clearfix colelem" id="u3241-4"><!-- content -->
     <p>Database</p>
</div>
<div style="min-height:500px">
</div>
{% endblock %}

web/templates/page_db_register.html
{% extends "page_base.html" %}

{% load staticfiles %}
{% load emph %}

{% block content %}
<div class="clearfix colelem" id="u3241-4"><!-- content -->
     <p>Register</p>
</div>
<div style="min-height:500px">
</div>
{% endblock %}

web/templates/page_db_search.html
{% extends "page_base.html" %}

{% load staticfiles %}
{% load emph %}

{% block content %}
    <style>
        #searchResult p {padding: 10px; }
        #searchResult h1 {font-size: 1.5em; font-weight: bold;}
        #searchResult input {border: 1px solid black; padding: 2px;}
        #searchResult p.hint {color: #c0c0c0; }
        #searchResult ul ul {margin-left: 15px; margin-bottom: 5px;}
        #searchResult ul ul ul {margin-left: 15px; margin-bottom: 5px;}
    </style>

    <div class="clearfix colelem" id="u3241-4"><!-- content -->
     <p>Search the DB</p>
    </div>

    <div class="clearfix colelem" id="pu965-3"><!-- group -->
    <div class="grpelem" id="u3575">
    <div id="htmlInclude"><!-- group -->
    <div id="searchResult">

    <br /><br />

    <form action="/search/" method="post">{% csrf_token %}
        {{ form.non_field_errors }}
        <table style="width:500px;">
            <tr>
                <td>Search target:</td>
                <td>
                    {{ form.search_target.errors }}
                    {{ form.search_target }}
                </td>
                <td>Search term:</td>
                <td>
                    {{ form.search_term.errors }}
                    {{ form.search_term }}
                </td>
                <td>&nbsp;&nbsp;<input type="submit" value="Submit" /></td>
            </tr>
        </table>
    </form>
    <br /><br /><br />  
    <h1>Search Result</h1>
    <br /><br />
    <ul>
    {% if tgt %}
        {% for item in items %}
            <li>
                <h1>{{ item.name|empha:sterm|safe }}</h1>
                <ul>
                    <li><b>Attributes</b></li>
                    {% for att in item.bdbattrib_set.all %}
                        {% if att.value %}
                            <li>{{ att.attrib_key.name }}/{{ att.value|empha:sterm|safe }}</li>
                        {% endif %}
                    {% endfor %}
                </ul>
                <ul>
                    <li><b>Diseases:</b></li>
                    {% for dise in item.dise.all %}
                        <li> {{ dise.name|empha:sterm|safe }}</li>
                        <ul>
                            <li><b>Symptoms:</b></li>
                            {% for symp in dise.symp.all %}
                               <li>{{ symp.name|empha:sterm|safe }}</li>
                            {% endfor %}
                        </ul>
                        <ul>
                            <li><b>Health Claims:</b></li>
                            {% for claim in dise.fcla.all %}
                               <li>{{ claim.name|empha:sterm|safe }}</li>
                            {% endfor %}
                        </ul>
                    {% endfor %}
                </ul>
                <ul>
                    <li><b>Pathways:</b></li>
                    {% for phys in item.phys.all %}
                        <li>{{ phys.name|empha:sterm|safe }}</li>
                    {% endfor %}
                </ul>
                <ul>
                    <li><b>Foods:</b></li>
                    {% for food in item.food.all %}
                        <li>{{ food.name|empha:sterm|safe }}</li>
                        <ul>
                            <li><b>Health Claims:</b></li>
                            {% for claim in food.fcla.all %}
                            <li>{{ claim.name|empha:sterm|safe }}</li>
                            {% endfor %}
                        </ul>
                    {% endfor %}
                </ul>
                <ul>
                    <li><b>Food Attributes:</b></li>
                    {% for fatt in item.fatt.all %}
                        <li>{{ fatt.name|empha:sterm|safe }}</li>
                    {% endfor %}
                </ul>

            </li>
        {% empty %}
             <p>No results found.</p> 
        {% endfor %}
    {% endif %}
    </ul>
</div>
</div>
</div>
</div>
{% endblock %}

web/templates/page_fc_food_composition_db.html
{% extends "page_base.html" %}

{% load staticfiles %}
{% load emph %}

{% block content %}
<div class="clearfix colelem" id="u3241-4"><!-- content -->
     <p>The New Zealand Food Composition Database</p>
</div>
<div style="min-height:500px">
</div>
{% endblock %}

web/templates/page_fc_make_claim.html
{% extends "page_base.html" %}

{% load staticfiles %}
{% load emph %}

{% block content %}
<div class="clearfix colelem" id="u3241-4"><!-- content -->
     <p>Making a Claim</p>
</div>
<div style="min-height:500px">
</div>
{% endblock %}

web/templates/page_fc_nz_info.html
{% extends "page_base.html" %}

{% load staticfiles %}
{% load emph %}

{% block content %}
<div class="clearfix colelem" id="u3241-4"><!-- content -->
     <p>New Zealand Information</p>
</div>
<div style="min-height:500px">
</div>
{% endblock %}

web/templates/page_fc_updates.html
{% extends "page_base.html" %}

{% load staticfiles %}
{% load emph %}

{% block content %}
<div class="clearfix colelem" id="u3241-4"><!-- content -->
     <p>Updates</p>
</div>
<div style="min-height:500px">
</div>
{% endblock %}

web/templates/page_fc_world_info.html
{% extends "page_base.html" %}

{% load staticfiles %}
{% load emph %}

{% block content %}
<div class="clearfix colelem" id="u3241-4"><!-- content -->
     <p>World Wide Information</p>
</div>
<div style="min-height:500px">
</div>
{% endblock %}

web/templates/page_food_claims.html
{% extends "page_base.html" %}

{% load staticfiles %}
{% load emph %}

{% block content %}
<div class="clearfix colelem" id="u3241-4"><!-- content -->
     <p>Food Claims</p>
</div>
<div style="min-height:500px">
</div>
{% endblock %}

web/templates/page_home.html
{% extends "page_base.html" %}

{% block content %}
    <div class="clearfix colelem" id="u3241-4"><!-- content -->
     <p>Welcome to Biomarkerz</p>
    </div>
    <div class="clearfix colelem" id="pu965-3"><!-- group -->
     <div class="clearfix grpelem" id="u965-3"><!-- content -->
      <p>&nbsp;</p>
     </div>
     <div class="clearfix grpelem" id="u3578-23"><!-- content -->
      <p class="Paragraph-Style"><span id="u3578">Biomarkers</span>&nbsp;are measurable biological parameters that are predictive of the risk of a serious disease when present at an abnormal level in the human body.&nbsp; Examples include Blood Pressure,&nbsp; blood and urine chemistry, imaging.</p>
      <p class="Paragraph-Style">&nbsp;</p>
      <p class="Paragraph-Style"><span id="u3578-5">A health claim on food</span><span id="u3578-6">&nbsp;</span>must show (most weight given to human trials)</p>
      <p class="Paragraph-Style">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; * A consistent association between the food or property of the food and the health effect.</p>
      <p class="Paragraph-Style">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; * The effect must be biologically plausible and</p>
      <p class="Paragraph-Style">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; * The amount of food needed to achieve the health effect must be able to be consumed as part of a normal diet.</p>
      <p>&nbsp;</p>
      <p class="Paragraph-Style---Dev-notes Menu">[To get an idea of the &quot;working&quot; part of the site please look under <a class="nonblock" href="/search/"><span id="u3578-17">Database &gt; Search</span></a>&nbsp;]</p>
      <p>&nbsp;</p>
     </div>
    </div>
{% endblock %}

web/templates/page_search.html
{% load staticfiles %}
{% load emph %}


<head>
</head>
<body>
    <form action="/search/" method="post">{% csrf_token %}
        {{ form.as_table }}
        <input type="submit" value="Submit" />
    </form>
    <ul>
    {% if tgt %}
        {% for item in items %}
            <li>
                {{ item.name|empha:sterm|safe }}
                <ul>
                    <li><b>Attributes</b></li>
                    {% for att in item.bdbattrib_set.all %}
                        {% if att.value %}
                            <li>{{ att.attrib_key.name }}/{{ att.value|empha:sterm|safe }}</li>
                        {% endif %}
                    {% endfor %}
                </ul>
                <ul>
                    <li><b>Diseases:</b></li>
                    {% for dise in item.dise.all %}
                        <li> {{ dise.name|empha:sterm|safe }}</li>
                        <ul>
                            <li><b>Symptoms:</b></li>
                            {% for symp in dise.symp.all %}
                               <li>{{ symp.name|empha:sterm|safe }}</li>
                            {% endfor %}
                        </ul>
                        <ul>
                            <li><b>Health Claims:</b></li>
                            {% for claim in dise.fcla.all %}
                               <li>{{ claim.name|empha:sterm|safe }}</li>
                            {% endfor %}
                        </ul>
                    {% endfor %}
                </ul>
                <ul>
                    <li><b>Pathways:</b></li>
                    {% for phys in item.phys.all %}
                        <li>{{ phys.name|empha:sterm|safe }}</li>
                    {% endfor %}
                </ul>
                <ul>
                    <li><b>Foods:</b></li>
                    {% for food in item.food.all %}
                        <li>{{ food.name|empha:sterm|safe }}</li>
                        <ul>
                            <li><b>Health Claims:</b></li>
                            {% for claim in food.fcla.all %}
                            <li>{{ claim.name|empha:sterm|safe }}</li>
                            {% endfor %}
                        </ul>
                    {% endfor %}
                </ul>
                <ul>
                    <li><b>Food Attributes:</b></li>
                    {% for fatt in item.fatt.all %}
                        <li>{{ fatt.name|empha:sterm|safe }}</li>
                    {% endfor %}
                </ul>

            </li>
        {% empty %}
             <p>No results found.</p> 
        {% endfor %}
    {% endif %}
    </ul>
</body>